import turtle as trt

def mål():
    trt.penup()
    trt.forward(200)
    trt.fillcolor("yellow")
    trt.pendown()
    trt.begin_fill()
    for i in range(2):
        trt.right(90)
        trt.forward(200)
        trt.right(90)
        trt.forward(300)
    trt.end_fill()
    
    trt.penup()
    trt.right(90)
    trt.forward(150)
    trt.right(90)
    trt.forward(250)
    trt.right(180)
    trt.pendown()
    trt.pendown()
    trt.left(90)
    trt.forward(100)
    trt.right(135)
    trt.forward(50)
    trt.left(90)
    trt.forward(50)
    trt.right(135)
    trt.forward(100)
    trt.penup()
    trt.left(90)
    trt.forward(15)
    trt.pendown()
    trt.left(75)
    trt.forward(100)
    trt.right(150)
    trt.forward(100)
    trt.penup()
    trt.right(180)
    trt.forward(50)
    trt.pendown()
    trt.left(75)
    trt.forward(28)
    trt.right(90)
    trt.penup()
    trt.forward(52)
    trt.right(90)
    trt.forward(15)
    trt.pendown()
    trt.circle(5)
    trt.penup()
    trt.right(90)
    trt.forward(100)
    trt.left(90)
    trt.forward(40)
    trt.pendown()
    trt.forward(50)
    trt.penup()
    trt.right(180)
    trt.forward(50)
    trt.right(90)
    trt.pendown()
    trt.forward(100)
    
    trt.penup()
    trt.left(90)
    trt.forward(60)
    trt.right(90)
    trt.forward(400)
    trt.right(180)
    trt.pendown()
    